# Generated by Django 4.1.7 on 2023-03-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('isOnline', models.BooleanField(default=True)),
                ('isVerified', models.BooleanField(default=True)),
                ('address1', models.CharField(default='', max_length=200)),
                ('address2', models.CharField(default='', max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=10)),
                ('zip', models.CharField(default='', max_length=200)),
                ('website', models.CharField(default='', max_length=250)),
                ('image_url', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
